-- TB_MEMBER_AUTH 테이블로부터 각 테이블을 JOIN하여 현재 가입중인(탈퇴하지 않은) 회원들의 정보를 보기좋게 출력. 패스워드 제외
SELECT
  MT.MEM_NO,
  MT.MEM_ID,
  MT.MEM_NICKNM,
  MT.MEM_ENABLE,
  A.AUTH_NO,
  A.AUTH_NM,
  A.AUTH_EXPLANATION
FROM
    TB_AUTH AS A
  INNER JOIN TB_MEMBER_AUTH AS MO ON (A.AUTH_NO = MO.AUTH_NO)
  INNER JOIN TB_MEMBER AS MT ON (MO.MEM_NO = MT.MEM_NO)
WHERE
  MT.MEM_ENABLE = 'Y'
ORDER BY
  MT.MEM_NO ASC, A.AUTH_NO ASC;

	
-- TB_MEMBER_AUTH 테이블의 MEM_NO - AUTH_NO 매핑을 각 테이블과 JOIN해서 보기좋게 출력
SELECT
  M.MEM_ID,
  MA.MEM_NO,
  MA.AUTH_NO,
  A.AUTH_NM			
FROM
    TB_MEMBER AS M
  LEFT OUTER JOIN TB_MEMBER_AUTH AS MA ON (MA.MEM_NO = M.MEM_NO)
  LEFT OUTER JOIN TB_AUTH AS A ON (MA.AUTH_NO = A.AUTH_NO)
ORDER BY
  M.MEM_NO ASC, A.AUTH_NO ASC;


-- TB_RESOURCE_AUTH 테이블의 RESOURCE_NO - AUTH_NO 매핑을 각 테이블과 JOIN해서 보기좋게 출력. 정렬 순서는 TB_RESOURCE의 SORT_ORDER에 따름
-- 연결된 권한이 없는 리소스도 출력
SELECT
  R.SORT_ORDER,
  R.RESOURCE_TYPE,
  HM.HTTP_METHOD_PATTERN,
  R.RESOURCE_PATTERN,
  RA.RESOURCE_NO,
  RA.AUTH_NO,
  A.AUTH_NM
FROM
    TB_RESOURCE AS R
  INNER JOIN TB_HTTP_METHOD AS HM ON (HM.HTTP_METHOD_NO = R.HTTP_METHOD_NO)
  LEFT OUTER JOIN TB_RESOURCE_AUTH AS RA ON (RA.RESOURCE_NO =  R.RESOURCE_NO)
  LEFT OUTER JOIN TB_AUTH AS A ON (RA.AUTH_NO = A.AUTH_NO)
WHERE
  R.RESOURCE_TYPE = 'url'
ORDER BY
  R.SORT_ORDER DESC, A.AUTH_NO DESC, HM.HTTP_METHOD_NO ASC;
  
-- 연결된 권한이 있는 리소스만 출력
SELECT
  R.SORT_ORDER,
  R.RESOURCE_TYPE,
  HM.HTTP_METHOD_PATTERN,
  R.RESOURCE_PATTERN,
  RA.RESOURCE_NO,
  RA.AUTH_NO,
  A.AUTH_NM
FROM
    TB_RESOURCE AS R
  INNER JOIN TB_HTTP_METHOD AS HM ON (HM.HTTP_METHOD_NO = R.HTTP_METHOD_NO)
  INNER JOIN TB_RESOURCE_AUTH AS RA ON (RA.RESOURCE_NO =  R.RESOURCE_NO)
  INNER JOIN TB_AUTH AS A ON (RA.AUTH_NO = A.AUTH_NO)
WHERE
  R.RESOURCE_TYPE = 'url'
ORDER BY
  R.SORT_ORDER DESC, A.AUTH_NO DESC, HM.HTTP_METHOD_NO ASC;


