-- 스키마 생성  SQL 입니다.
﻿-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- 데이터베이스 제거
drop database security;

-- 데이터베이스 선택
USE SECURITY;

-- 데이터베이스 생성
CREATE DATABASE SECURITY;

-- TB_AUTH Table Create SQL
CREATE TABLE TB_AUTH
(
    AUTH_NO           INT            NOT NULL    AUTO_INCREMENT COMMENT '권한 일련 번호', 
    AUTH_NM           VARCHAR(50)    NOT NULL     COMMENT '권한 명', 
    AUTH_EXPLANATION  VARCHAR(50)    NOT NULL     COMMENT '권한 설명', 
    PRIMARY KEY (AUTH_NO)
);

ALTER TABLE TB_AUTH COMMENT '권한 테이블';
ALTER TABLE TB_AUTH ADD UNIQUE KEY(AUTH_NM);

-- TB_MEMBER Table Create SQL
CREATE TABLE TB_MEMBER
(
    MEM_NO        INT             NOT NULL    AUTO_INCREMENT COMMENT '계정 일련 번호', 
    MEM_ID        VARCHAR(50)     NOT NULL     COMMENT '계정 ID', 
    MEM_PASSWORD  VARCHAR(300)    NOT NULL     COMMENT '계정 PW', 
    MEM_NICKNM  VARCHAR(30)     NOT NULL     COMMENT '계정 이름', 
    MEM_ENABLE    CHAR(1)         NOT NULL     COMMENT '계정 사용 여부', 
    PRIMARY KEY (MEM_NO)
);

ALTER TABLE TB_MEMBER COMMENT '계정 테이블';

-- TB_RESOURCE Table Create SQL
CREATE TABLE TB_RESOURCE
(
    RESOURCE_NO       INT              NOT NULL    AUTO_INCREMENT COMMENT '리소스 일련 번호',
    RESOURCE_NM     VARCHAR(50)     NOT NULL     COMMENT '리소스 이름',
    RESOURCE_PATTERN  VARCHAR(100)    NOT NULL     COMMENT '리소스 패턴',
    RESOURCE_TYPE     VARCHAR(10)     NOT NULL     COMMENT '리소스 타입(url : URL, method : Method)',
    SORT_ORDER        INT              NOT NULL     COMMENT '순서',
    PRIMARY KEY (RESOURCE_NO)
);

ALTER TABLE TB_RESOURCE COMMENT '리소스 테이블';
ALTER TABLE TB_RESOURCE ADD UNIQUE KEY(RESOURCE_NM);

-- TB_MEMBER_AUTH Table Create SQL
CREATE TABLE TB_MEMBER_AUTH
(
    MEM_NO   INT    NOT NULL     COMMENT '계정 일련 번호', 
    AUTH_NO  INT    NOT NULL     COMMENT '권한 일련 번호',
	PRIMARY KEY(MEM_NO, AUTH_NO)
);

ALTER TABLE TB_MEMBER_AUTH COMMENT '계정-권한 테이블';

ALTER TABLE TB_MEMBER_AUTH ADD CONSTRAINT FK_TB_MEMBER_AUTH_MEM_NO_TB_MEMBER_MEM_NO FOREIGN KEY (MEM_NO)
 REFERENCES TB_MEMBER (MEM_NO)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_MEMBER_AUTH ADD CONSTRAINT FK_TB_MEMBER_AUTH_AUTH_NO_TB_AUTH_AUTH_NO FOREIGN KEY (AUTH_NO)
 REFERENCES TB_AUTH (AUTH_NO)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TB_RESOURCE_AUTH Table Create SQL
CREATE TABLE TB_RESOURCE_AUTH
(
    RESOURCE_NO  INT    NOT NULL     COMMENT '리소스 일련 번호', 
    AUTH_NO      INT    NOT NULL     COMMENT '권한 일련 번호',
	PRIMARY KEY(RESOURCE_NO, AUTH_NO)
);

ALTER TABLE TB_RESOURCE_AUTH COMMENT '리소스-권한 테이블';

ALTER TABLE TB_RESOURCE_AUTH ADD CONSTRAINT FK_TB_RESOURCE_AUTH_RESOURCE_NO_TB_RESOURCE_RESOURCE_NO FOREIGN KEY (RESOURCE_NO)
 REFERENCES TB_RESOURCE (RESOURCE_NO)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TB_RESOURCE_AUTH ADD CONSTRAINT FK_TB_RESOURCE_AUTH_AUTH_NO_TB_AUTH_AUTH_NO FOREIGN KEY (AUTH_NO)
 REFERENCES TB_AUTH (AUTH_NO)  ON DELETE RESTRICT ON UPDATE RESTRICT;

