
USE security;

CREATE TABLE `tb_block_member` (
  `BLOCK_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT '차단 일련 번호',
  `MEM_NO` int(11) NOT NULL COMMENT '계정 일련 번호',
  `BLOCK_START_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '차단 시작 일자',
  `BLOCK_EXPIRE_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '차단 만료 일자',
  `BLOCK_CAUSE` varchar(300) NOT NULL COMMENT '차단 사유',
  PRIMARY KEY (`BLOCK_NO`),
  KEY `FK_TB_BLOCK_MEMBER_MEM_NO_TB_MEMBER_MEM_NO` (`MEM_NO`),
  CONSTRAINT `FK_TB_BLOCK_MEMBER_MEM_NO_TB_MEMBER_MEM_NO` FOREIGN KEY (`MEM_NO`) REFERENCES `tb_member` (`MEM_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='차단 계정 테이블';


INSERT INTO tb_block_member(BLOCK_NO,MEM_NO,BLOCK_START_DATE,BLOCK_EXPIRE_DATE,BLOCK_CAUSE) VALUES (1,11,'2018-04-26 14:33:32','2018-03-30 15:54:54','과거');
INSERT INTO tb_block_member(BLOCK_NO,MEM_NO,BLOCK_START_DATE,BLOCK_EXPIRE_DATE,BLOCK_CAUSE) VALUES (2,11,'2018-03-25 15:54:54','2019-03-30 15:54:54','현재');
INSERT INTO tb_block_member(BLOCK_NO,MEM_NO,BLOCK_START_DATE,BLOCK_EXPIRE_DATE,BLOCK_CAUSE) VALUES (3,11,'2019-03-25 15:54:54','2019-03-30 15:54:54','미래');
