
USE security;

CREATE TABLE `tb_member_auth` (
  `MEM_NO` int(11) NOT NULL COMMENT '계정 일련 번호',
  `AUTH_NO` int(11) NOT NULL COMMENT '권한 일련 번호',
  PRIMARY KEY (`MEM_NO`,`AUTH_NO`),
  KEY `FK_TB_MEMBER_AUTH_AUTH_NO_TB_AUTH_AUTH_NO` (`AUTH_NO`),
  CONSTRAINT `FK_TB_MEMBER_AUTH_AUTH_NO_TB_AUTH_AUTH_NO` FOREIGN KEY (`AUTH_NO`) REFERENCES `tb_auth` (`AUTH_NO`),
  CONSTRAINT `FK_TB_MEMBER_AUTH_MEM_NO_TB_MEMBER_MEM_NO` FOREIGN KEY (`MEM_NO`) REFERENCES `tb_member` (`MEM_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='계정-권한 테이블';


INSERT INTO tb_member_auth(MEM_NO,AUTH_NO) VALUES (3,1);
INSERT INTO tb_member_auth(MEM_NO,AUTH_NO) VALUES (2,2);
INSERT INTO tb_member_auth(MEM_NO,AUTH_NO) VALUES (11,2);
INSERT INTO tb_member_auth(MEM_NO,AUTH_NO) VALUES (1,3);
