USE security;

CREATE TABLE `tb_resource_auth` (
  `RESOURCE_NO` int(11) NOT NULL COMMENT '리소스 일련 번호',
  `AUTH_NO` int(11) NOT NULL COMMENT '권한 일련 번호',
  PRIMARY KEY (`RESOURCE_NO`,`AUTH_NO`),
  KEY `FK_TB_RESOURCE_AUTH_AUTH_NO_TB_AUTH_AUTH_NO` (`AUTH_NO`),
  CONSTRAINT `FK_TB_RESOURCE_AUTH_AUTH_NO_TB_AUTH_AUTH_NO` FOREIGN KEY (`AUTH_NO`) REFERENCES `tb_auth` (`AUTH_NO`),
  CONSTRAINT `FK_TB_RESOURCE_AUTH_RESOURCE_NO_TB_RESOURCE_RESOURCE_NO` FOREIGN KEY (`RESOURCE_NO`) REFERENCES `tb_resource` (`RESOURCE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='리소스-권한 테이블';


INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (1,1);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (2,1);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (4,1);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (5,1);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (4,2);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (5,2);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (1,3);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (2,3);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (4,3);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (5,3);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (3,4);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (4,4);
INSERT INTO `tb_resource_auth`(`RESOURCE_NO`,`AUTH_NO`) VALUES (5,4);
