USE security;

CREATE TABLE `tb_resource` (
  `RESOURCE_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT '리소스 일련 번호',
  `HTTP_METHOD_NO` int(11) NOT NULL COMMENT 'HTTP 메소드 일련 번호',
  `RESOURCE_NM` varchar(50) NOT NULL COMMENT '리소스 이름',
  `RESOURCE_PATTERN` varchar(100) NOT NULL COMMENT '리소스 패턴',
  `RESOURCE_TYPE` varchar(10) NOT NULL COMMENT '리소스 타입(url : URL, method : Method)',
  `SORT_ORDER` int(11) NOT NULL COMMENT '순서',
  PRIMARY KEY (`RESOURCE_NO`),
  UNIQUE KEY `RESOURCE_NM` (`RESOURCE_NM`),
  UNIQUE KEY `RESOURCE_PATTERN` (`RESOURCE_PATTERN`),
  CONSTRAINT `FK_TB_RESOURCE_HTTP_METHOD_NO_TB_HTTP_METHOD_HTTP_METHOD_NO` FOREIGN KEY (`HTTP_METHOD_NO`) REFERENCES `TB_HTTP_METHOD` (`HTTP_METHOD_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COMMENT='리소스 테이블';


INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (1,1,'hello 페이지','/admin/hello','url',40100);
INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (2,1,'관리자 페이지','/admin/**','url',40000);
INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (3,1,'로그인 페이지','/login','url',20000);
INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (4,1,'메인 페이지','/main','url',30000);
INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (5,1,'모든 페이지','/**','url',10000);
INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (10,1,'리소스 관리 페이지','/resource/**','url',50000);
INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (11,1,'리소스 관리 페이지 이동','/resource/edit','url',50100);
INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (12,1,'모든 리소스 목록 중 해당 페이지 만큼 반환','/resource','url',50200);
INSERT INTO `tb_resource`(`RESOURCE_NO`,`HTTP_METHOD_NO`,`RESOURCE_NM`,`RESOURCE_PATTERN`,`RESOURCE_TYPE`,`SORT_ORDER`) VALUES (13,1,'모든 리소스 목록 반환','/resource/page/*','url',50210);
